dh_cloud_run.yml

diff --git a/.github/workflows/dh_cloud_run.yml b/.github/workflows/dh_cloud_run.yml
--- a/.github/workflows/dh_cloud_run.yml
+++ b/.github/workflows/dh_cloud_run.yml
@@ -29,8 +29,19 @@ jobs:
 
     - name: Install GKE gcloud auth plugin
       run: |
-        curl -Lo gke-gcloud-auth-plugin https://dl.google.com/cloudsdk/gke-gcloud-auth-plugin-linux-amd64.tar.gz
+        # Download the auth plugin
+        curl -Lo gke-gcloud-auth-plugin-linux-amd64.tar.gz https://dl.google.com/cloudsdk/gke-gcloud-auth-plugin-linux-amd64.tar.gz
+
+        # Verify if the file exists
+        if [ ! -f "gke-gcloud-auth-plugin-linux-amd64.tar.gz" ]; then
+          echo "File not found!"
+          exit 1
+        fi
+
+        # Extract the tar file
         tar -xvzf gke-gcloud-auth-plugin-linux-amd64.tar.gz
+
+        # Move the plugin to /usr/local/bin/
         sudo mv gke-gcloud-auth-plugin /usr/local/bin/
 
     - name: Configure Docker Auth
